env:
  browser: true
  es2021: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/order: 2
  react/jsx-filename-extension:
    - 0
    - allow: as-needed
  import/prefer-default-export: 0
  react/prop-types: 0
  react/no-array-index-key: 0
  no-underscore-dangle:
    - 2
    - allow:
        - _northEast
        - _southWest
  no-console: 0
